CREATE TABLE IF NOT EXISTS patient (
ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
BIRTHDAY VARCHAR(100) NOT NULL,
ID_CARD_NO VARCHAR(100) NOT NULL,
PHONE_NUMBER VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS visit (
ID INT AUTO_INCREMENT PRIMARY KEY,
DATE_TIME TIMESTAMP NOT NULL,
PATIENT_ID INT,
FOREIGN KEY (PATIENT_ID) REFERENCES patient (ID)
);
CREATE TABLE IF NOT EXISTS doctor(
ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
SPECIALIZATION VARCHAR(100) NOT NULL
);

INSERT INTO patient (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BIRTHDAY, ID_CARD_NO, PHONE_NUMBER)
VALUES ('John', 'Doe', 'password123', 'john.doe@example.com', '1990-05-15', '123456789', '1234567890');

INSERT INTO patient (FIRST_NAME, LAST_NAME, PASSWORD, EMAIL, BIRTHDAY, ID_CARD_NO, PHONE_NUMBER)
VALUES ('Jane', 'Smith', 'abc123', 'jane.smith@example.com', '1985-09-23', '987654321', '9876543210');

INSERT INTO doctor (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, SPECIALIZATION)
VALUES ('Dr. James', 'Smith', 'james.smith@example.com', 'doctor123', 'Cardiology');

INSERT INTO doctor (FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, SPECIALIZATION)
VALUES ('Dr. Emily', 'Johnson', 'emily.johnson@example.com', 'doctor456', 'Dermatology');

INSERT INTO visit (DATE_TIME, PATIENT_ID)
VALUES ('2024-07-12 10:00:00', 1);

INSERT INTO visit (DATE_TIME, PATIENT_ID)
VALUES ('2024-07-13 14:30:00', 2);

INSERT INTO visit (DATE_TIME, PATIENT_ID)
VALUES ('2024-07-13 14:30:00', DEFAULT);